/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ReturnPolicyRouteImport } from './routes/return-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as CollectionSlugRouteImport } from './routes/collection.$slug'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnPolicyRoute = ReturnPolicyRouteImport.update({
  id: '/return-policy',
  path: '/return-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionSlugRoute = CollectionSlugRouteImport.update({
  id: '/collection/$slug',
  path: '/collection/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/search': typeof SearchRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/product/$handle': typeof ProductHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/search': typeof SearchRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/product/$handle': typeof ProductHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/search': typeof SearchRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/product/$handle': typeof ProductHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/cart'
    | '/contact'
    | '/faq'
    | '/privacy-policy'
    | '/return-policy'
    | '/search'
    | '/shipping-policy'
    | '/shop'
    | '/sitemap.xml'
    | '/terms'
    | '/thank-you'
    | '/track-order'
    | '/wishlist'
    | '/collection/$slug'
    | '/product/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/cart'
    | '/contact'
    | '/faq'
    | '/privacy-policy'
    | '/return-policy'
    | '/search'
    | '/shipping-policy'
    | '/shop'
    | '/sitemap.xml'
    | '/terms'
    | '/thank-you'
    | '/track-order'
    | '/wishlist'
    | '/collection/$slug'
    | '/product/$handle'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/cart'
    | '/contact'
    | '/faq'
    | '/privacy-policy'
    | '/return-policy'
    | '/search'
    | '/shipping-policy'
    | '/shop'
    | '/sitemap.xml'
    | '/terms'
    | '/thank-you'
    | '/track-order'
    | '/wishlist'
    | '/collection/$slug'
    | '/product/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ReturnPolicyRoute: typeof ReturnPolicyRoute
  SearchRoute: typeof SearchRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
  TrackOrderRoute: typeof TrackOrderRoute
  WishlistRoute: typeof WishlistRoute
  CollectionSlugRoute: typeof CollectionSlugRoute
  ProductHandleRoute: typeof ProductHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return-policy': {
      id: '/return-policy'
      path: '/return-policy'
      fullPath: '/return-policy'
      preLoaderRoute: typeof ReturnPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$slug': {
      id: '/collection/$slug'
      path: '/collection/$slug'
      fullPath: '/collection/$slug'
      preLoaderRoute: typeof CollectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ReturnPolicyRoute: ReturnPolicyRoute,
  SearchRoute: SearchRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
  TrackOrderRoute: TrackOrderRoute,
  WishlistRoute: WishlistRoute,
  CollectionSlugRoute: CollectionSlugRoute,
  ProductHandleRoute: ProductHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
